initial_positions:
  robot2_shoulder_pan_joint: 0.0
  robot2_shoulder_lift_joint: -1.5707
  robot2_elbow_joint: 0.0
  robot2_wrist_1_joint: -1.5707
  robot2_wrist_2_joint: 0.0
  robot2_wrist_3_joint: 0.0
  robot2_finger_joint: 0.0
