joint_limits:
  robot2_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 10.0
  robot2_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 10.0
  robot2_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 10.0
  robot2_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.2831853071795862
    has_acceleration_limits: true
    max_acceleration: 10.0
  robot2_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.2831853071795862
    has_acceleration_limits: true
    max_acceleration: 10.0
  robot2_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.2831853071795862
    has_acceleration_limits: true
    max_acceleration: 10.0
  robot2_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 2.0
