initial_positions:
  robot3_shoulder_pan_joint: 0.0
  robot3_shoulder_lift_joint: -1.5707
  robot3_elbow_joint: 0.0
  robot3_wrist_1_joint: -1.5707
  robot3_wrist_2_joint: 0.0
  robot3_wrist_3_joint: 0.0
  robot3_finger_joint: 0.0
